In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../canna/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/canna/canna'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [6]:
data = pd.read_csv("cannabis.csv")

In [7]:
data.head()

Strain    Type  Rating                                     Effects  \
0          100-Og  hybrid     4.0  Creative,Energetic,Tingly,Euphoric,Relaxed   
1  98-White-Widow  hybrid     4.7    Relaxed,Aroused,Creative,Happy,Energetic   
2            1024  sativa     4.4   Uplifted,Happy,Relaxed,Energetic,Creative   
3        13-Dawgs  hybrid     4.2     Tingly,Creative,Hungry,Relaxed,Uplifted   
4        24K-Gold  hybrid     4.6   Happy,Relaxed,Euphoric,Uplifted,Talkative   

                      Flavor  \
0        Earthy,Sweet,Citrus   
1      Flowery,Violet,Diesel   
2    Spicy/Herbal,Sage,Woody   
3  Apricot,Citrus,Grapefruit   
4       Citrus,Earthy,Orange   

                                         Description  
0  $100 OG is a 50/50 hybrid strain that packs a ...  
1  The ‘98 Aloha White Widow is an especially pot...  
2  1024 is a sativa-dominant hybrid bred in Spain...  
3  13 Dawgs is a hybrid of G13 and Chemdawg genet...  
4  Also known as Kosher Tangie, 24k Gold is a 60%...

In [8]:
data.describe()

Rating
count  2351.000000
mean      4.310634
std       0.836394
min       0.000000
25%       4.200000
50%       4.400000
75%       4.700000
max       5.000000

In [9]:
print(data["Flavor"].isnull().values.sum())
data["Flavor"] = data["Flavor"].fillna("None")

46


In [10]:
total_flavor = []
max_len = 0
total_flavor.append("None")
for val in data["Flavor"].values:
    print(val)
    val = val.split(",")
    
    if len(val) > max_len:
        max_len = len(val)
    
    for f in val:
        if f not in total_flavor:
            total_flavor.append(f)
            

Earthy,Sweet,Citrus
Flowery,Violet,Diesel
Spicy/Herbal,Sage,Woody
Apricot,Citrus,Grapefruit
Citrus,Earthy,Orange
None
Earthy,Sweet,Pungent
Citrus,Pungent,Earthy
Earthy,Woody,Flowery
Earthy,Grape,Sweet
Pine,Diesel
Earthy,Pine,Skunk
Earthy,Woody,Pine
Earthy,Woody,Pungent
Citrus,Earthy,Pine
Earthy,Diesel,Flowery
None
Earthy,Sweet,Berry
Earthy,Pungent,Berry
Citrus,Pungent,Sweet
Diesel,Pepper,Earthy
Earthy,Woody,Citrus
Earthy,Pine,Woody
Earthy,Pungent,Woody
Earthy,Pungent,Citrus
Menthol,Blue,Cheese,Chemical
Earthy,Pine,Diesel
Earthy,Sweet,Pungent
Earthy,Diesel,Spicy/Herbal
Earthy,Sweet,Woody
Earthy,Mango,Lemon
Lemon,Diesel,Earthy
None
Sweet,Flowery,Earthy
Pungent,Lemon,Peach
Sweet,Vanilla
Earthy,Diesel,Chemical
Nutty,Earthy,Chestnut
Earthy,Flowery,Tea
Earthy,Flowery,Woody
Skunk,Woody,Sweet
Earthy,Diesel,Pungent
Flowery,Diesel,Sweet
Earthy,Sweet,Pine
Lemon,Citrus,Sweet
Flowery,Chemical,Spicy/Herbal
Sweet,Flowery,Skunk
Citrus,Skunk
Earthy,Sweet,Woody
Sweet,Pine,Woody
Woody,Pine,Pungent
Tobacc

Earthy,Citrus,Spicy/Herbal
Earthy,Citrus,Flowery
Tropical,Pine,Earthy
Diesel,Berry,Tropical
Sweet,Pungent,Skunk
Sweet,Berry,Blueberry
Berry,Earthy,Spicy/Herbal
Earthy,Pungent,Skunk
Lemon,Citrus,Earthy
Earthy,Pine,Grape
Earthy,Skunk,Sweet
Spicy/Herbal,Pepper,Pungent
Blueberry,Strawberry,Pineapple
Earthy,Pine,Diesel
Berry,Lavender,Earthy
Earthy,Pungent,Sweet
Earthy,Diesel,Pungent
Diesel,Earthy,Skunk
Cheese,Pungent,Skunk
Plum,Earthy,Ammonia
Grape,Earthy,Sweet
Pungent,Earthy,Sweet
Citrus,Mango,Sweet
Sweet,Earthy,Pine
Earthy
Lavender,Ammonia,Sweet
Spicy/Herbal,Pepper,Sweet
Spicy/Herbal,Pepper,Earthy
Sweet,Earthy,Spicy/Herbal
Earthy,Spicy/Herbal,Pine
None
Earthy,Spicy/Herbal,Pungent
Sweet,Flowery,Honey
Diesel,Earthy,Woody
Earthy,Skunk,Spicy/Herbal
Tropical,Pungent,Earthy
Citrus,Sweet,Lemon
Spicy/Herbal,Flowery
Sweet,Earthy,Pungent
Sweet,Lime,Apple
Sweet,Pungent,Spicy/Herbal
Sweet,Flowery,Earthy
None
Earthy,Sweet,Pungent
Sweet,Strawberry,Citrus
Pungent,Earthy,Berry
Earthy,Skunk,Pungent
Sweet,

Earthy,Pine,Minty
Citrus,Diesel,Pungent
Citrus,Pepper,Lime
Orange,Berry,Blueberry
Sweet,Lemon,Earthy
Honey,Lemon,Pungent
Pungent,Sweet,Flowery
Earthy,Lemon,Sweet
Berry,Blueberry,Sweet
Earthy,Vanilla,Sweet
Lemon,Sweet,Pine
Earthy,Sweet,Citrus
Earthy,Spicy/Herbal,Sage
Earthy,Sweet,Woody
Citrus,Sweet,Berry
Sweet,Berry,Pineapple
Ammonia,Diesel,Spicy/Herbal
Earthy,Sweet,Citrus
Earthy,Woody,Sweet
None
None
Earthy,Sweet,Tropical
Earthy,Woody,Cheese
Diesel,Citrus,Grapefruit
Diesel,Earthy,Pungent
Flowery,Pine,Earthy
Sweet,Citrus,Spicy/Herbal
Earthy,Honey,Pungent
Earthy,Spicy/Herbal,Woody
Sweet,Earthy,Citrus
Earthy,Grapefruit,Sweet
None
Citrus,Pine,Honey
Pungent,Tree,Fruit,Earthy
Earthy,Sage,Pine
Sweet,Earthy,Diesel
Sweet,Berry,Earthy
Sweet,Berry,Pungent
Pungent,Sweet,Woody
Sweet,Earthy,Diesel
Earthy,Berry,Grape
Pepper,Pungent,Chemical
Citrus,Pine,Earthy
Sweet,Pine,Woody
Lemon,Sweet,Citrus
Grape,Citrus,Sweet
Sweet,Citrus,Pungent
Earthy,Woody,Spicy/Herbal
Earthy,Pungent,Skunk
Tropical,Earthy,Wood

Skunk,Citrus,Diesel
Apple,Sweet,Pungent
Sweet,Diesel,Tree,Fruit
Diesel,Apricot,Pine
Earthy,Diesel,Flowery
Sweet,Pungent,Earthy
Diesel,Earthy,Sweet
Cheese,Pungent,Lime
None
Diesel,Sweet,Earthy
Sweet,Lime,Earthy
Diesel,Sweet,Earthy
Diesel,Earthy,Sweet
Diesel,Pungent,Earthy
Diesel,Earthy,Blueberry
Diesel,Pungent,Flowery
Berry,Earthy,Pine
Grape,Sweet,Berry
Citrus,Lemon,Pungent
Diesel,Pungent,Skunk
Citrus,Sweet,Tropical
Berry,Sweet,Citrus
Earthy,Pungent,Tree,Fruit
Earthy,Pungent,Diesel
Citrus,Pungent,Earthy
Lemon,Citrus,Earthy
Citrus,Nutty,Earthy
Diesel,Pungent,Pine
Citrus,Earthy,Flowery
Sweet,Citrus,Berry
Citrus,Earthy,Pine
Diesel,Skunk,Pungent
Ammonia,Citrus,Coffee
Citrus,Sweet,Spicy/Herbal
Strawberry,Sweet,Diesel
Sweet,Diesel,Citrus
Citrus,Diesel,Orange
Citrus,Diesel,Sweet
Earthy,Diesel,Flowery
Pungent,Diesel,Sweet
Sweet,Tropical,Pungent
Earthy,Mango,Tropical
Sweet
None
Sweet,Berry,Blueberry
None
Skunk,Mango,Sweet
Lemon
Earthy,Flowery,Berry
Earthy,Sweet,Pungent
Sweet,Citrus,Pine
Sweet,Ea

In [11]:
print(len(total_flavor))
print(max_len)

50
4


In [12]:
print(data["Effects"].isnull().values.sum())
# data["Flavor"] = data["Flavor"].fillna("None")

0


In [13]:
total_effects = []
max_len = 0
for val in data["Effects"].values:
    print(val)
    val = val.split(",")
    
    if len(val) > max_len:
        max_len = len(val)
        
    for e in val:
        if e not in total_effects:
            total_effects.append(e)

Creative,Energetic,Tingly,Euphoric,Relaxed
Relaxed,Aroused,Creative,Happy,Energetic
Uplifted,Happy,Relaxed,Energetic,Creative
Tingly,Creative,Hungry,Relaxed,Uplifted
Happy,Relaxed,Euphoric,Uplifted,Talkative
None
Relaxed,Euphoric,Happy,Uplifted,Hungry
Relaxed,Happy,Euphoric,Uplifted,Giggly
Uplifted,Focused,Happy,Talkative,Relaxed
Relaxed,Tingly,Happy,Euphoric,Uplifted
Energetic,Happy,Talkative,Uplifted
Relaxed,Euphoric,Sleepy,Happy,Talkative
Relaxed,Focused,Euphoric,Uplifted,Aroused
Euphoric,Happy,Uplifted,Talkative,Creative
Relaxed,Uplifted,Happy,Creative,Euphoric
Relaxed,Happy,Euphoric,Giggly,Sleepy
None
Relaxed,Sleepy,Euphoric,Happy,Hungry
Relaxed,Euphoric,Happy,Hungry,Uplifted
Relaxed,Focused,Happy,Sleepy,Uplifted
Relaxed,Happy,Euphoric,Uplifted,Sleepy
Creative,Euphoric,Relaxed,Happy,Hungry
Relaxed,Happy,Uplifted,Focused,Euphoric
Happy,Relaxed,Uplifted,Euphoric,Energetic
Happy,Energetic,Uplifted,Creative,Relaxed
Uplifted,Euphoric,Giggly,Energetic,Sleepy
Relaxed,Euphoric,Sleepy,Happ

Relaxed,Happy,Creative,Sleepy,Aroused
Euphoric,Relaxed,Happy,Uplifted,Tingly
Euphoric,Hungry,Relaxed,Sleepy,Happy
Sleepy,Tingly,Happy,Relaxed,Uplifted
Happy,Relaxed,Focused,Euphoric,Uplifted
Sleepy,Relaxed,Creative,Hungry,Happy
None
Relaxed,Happy,Uplifted,Euphoric,Focused
Happy,Energetic,Creative,Focused,Uplifted
Focused,Happy,Relaxed,Euphoric,Sleepy
Relaxed,Euphoric,Happy,Uplifted,Creative
Happy,Relaxed,Uplifted,Euphoric,Giggly
Relaxed,Sleepy,Happy,Hungry,Talkative
Relaxed,Happy,Euphoric,Uplifted,Aroused
Relaxed,Happy,Euphoric,Hungry,Giggly
Aroused,Creative,Euphoric,Happy,Uplifted
Happy,Relaxed,Euphoric,Energetic,Uplifted
Relaxed,Tingly,Happy,Giggly,Uplifted
Relaxed,Euphoric,Uplifted,Sleepy,Happy
None
Euphoric,Relaxed,Sleepy,Energetic,Happy
Relaxed,Happy,Euphoric,Uplifted,Hungry
Euphoric,Happy,Creative,Relaxed,Focused
Happy,Relaxed,Euphoric,Creative,Focused
Creative,Euphoric,Focused,Tingly,Sleepy
Relaxed,Euphoric,Happy,Sleepy,Uplifted
Relaxed,Happy,Euphoric,Uplifted,Hungry
Relaxed,Hap

Relaxed,Euphoric,Happy,Sleepy,Uplifted
Relaxed,Happy,Hungry,Tingly,Uplifted
Relaxed,Euphoric,Hungry,Giggly,Happy
Relaxed,Happy,Uplifted,Euphoric,Creative
None
Happy,Relaxed,Uplifted,Euphoric,Creative
Euphoric,Happy,Aroused,Creative,Giggly
Hungry,Relaxed,Tingly,Sleepy,Euphoric
Hungry,Relaxed,Happy,Uplifted,Energetic
Euphoric,Happy,Creative,Energetic,Focused
Happy,Relaxed,Talkative,Uplifted,Euphoric
Creative,Euphoric,Happy,Relaxed
Aroused,Tingly,Uplifted,Euphoric,Happy
Relaxed,Sleepy,Euphoric,Happy,Uplifted
Relaxed,Creative,Euphoric,Uplifted,Happy
Euphoric,Sleepy,Happy,Relaxed,Focused
Relaxed,Happy,Hungry,Focused,Sleepy
Uplifted,Relaxed,Energetic,Happy,Focused
Happy,Energetic,Euphoric,Uplifted,Talkative
Creative,Energetic,Euphoric,Focused,Happy
Happy,Euphoric,Relaxed,Focused,Creative
None
Sleepy,Happy,Relaxed,Tingly,Hungry
Euphoric,Uplifted,Relaxed,Happy,Tingly
Happy,Relaxed,Uplifted,Focused,Euphoric
Happy,Relaxed,Sleepy,Uplifted,Euphoric
Euphoric,Relaxed,Happy,Creative,Talkative
Relaxed

Happy,Hungry,Relaxed,Focused,Creative
Uplifted,Creative,Euphoric,Energetic,Happy
Euphoric,Uplifted,Creative,Energetic,Focused
Relaxed,Euphoric,Happy,Creative,Energetic
Happy,Giggly,Tingly,Uplifted,Relaxed
Euphoric,Happy,Relaxed,Creative,Energetic
Tingly,Focused,Talkative,Uplifted,Energetic
Tingly,Relaxed,Sleepy,Uplifted,Creative
Uplifted,Happy,Relaxed,Talkative,Energetic
Relaxed,Happy,Sleepy,Euphoric,Uplifted
Relaxed,Happy,Sleepy,Euphoric,Hungry
Euphoric,Relaxed,Happy,Sleepy,Uplifted
Happy,Energetic,Uplifted,Focused,Tingly
Happy,Hungry,Uplifted,Energetic,Focused
Relaxed,Euphoric,Happy,Focused,Uplifted
Euphoric,Energetic,Uplifted,Happy,Focused
Relaxed,Focused,Happy,Giggly,Sleepy
Relaxed,Sleepy,Happy,Euphoric,Hungry
Relaxed,Happy,Sleepy,Euphoric,Uplifted
Creative,Aroused,Uplifted,Energetic,Euphoric
None
Euphoric,Relaxed,Focused,Creative,Hungry
Uplifted,Happy,Giggly,Relaxed,Focused
Aroused,Uplifted,Energetic,Sleepy,Tingly
Relaxed,Happy,Uplifted,Sleepy,Focused
Relaxed,Euphoric,Uplifted,Foc

Creative,Tingly,Uplifted,Energetic,Happy
Happy,Giggly,Energetic,Focused,Euphoric
Happy,Energetic,Uplifted,Talkative,Focused
Relaxed,Happy,Euphoric,Giggly,Aroused
Happy,Uplifted,Energetic,Euphoric,Focused
Relaxed,Happy,Hungry,Euphoric,Creative
Happy,Uplifted,Energetic,Euphoric,Relaxed
Happy,Uplifted,Creative,Euphoric,Giggly
Relaxed,Sleepy,Euphoric,Happy,Hungry
Uplifted,Happy,Euphoric,Relaxed,Focused
Uplifted,Happy,Euphoric,Creative,Energetic
Relaxed,Uplifted,Happy,Focused,Giggly
Happy,Euphoric,Talkative,Sleepy,Uplifted
Euphoric,Energetic,Happy,Uplifted,Relaxed
Happy,Relaxed,Uplifted,Focused,Giggly
Happy,Relaxed,Sleepy,Euphoric,Giggly
Relaxed,Happy,Euphoric,Uplifted,Giggly
Relaxed,Sleepy,Euphoric,Happy,Hungry
Relaxed,Happy,Euphoric,Tingly,Uplifted
Euphoric,Relaxed,Happy,Creative,Energetic
Happy,Uplifted,Relaxed,Euphoric,Creative
Relaxed,Focused,Euphoric,Uplifted,Happy
Relaxed,Focused,Uplifted,Talkative,Happy
Hungry,Relaxed,Focused,Creative,Giggly
Relaxed,Tingly,Giggly,Happy,Hungry
Relaxe

In [14]:
print(len(total_effects))
print(max_len)

16
5


# Split the Flavor Column

In [15]:
split_data = data["Flavor"].str.split(",")
split_data = split_data.to_list()
names = ["Flavor_1", "Flavor_2", "Flavor_3", "Flavor_4"]
new_flavor = pd.DataFrame(split_data, columns=names)

In [16]:
new_flavor = new_flavor.fillna("None")

In [17]:
new_flavor["Flavor_4"].isnull().values.sum()

# 2308 values of Flavor_4 column are Null, therefore dropping it.
new_flavor = new_flavor.drop(columns=["Flavor_4"])

new_flavor

Flavor_1 Flavor_2      Flavor_3
0           Earthy    Sweet        Citrus
1          Flowery   Violet        Diesel
2     Spicy/Herbal     Sage         Woody
3          Apricot   Citrus    Grapefruit
4           Citrus   Earthy        Orange
...            ...      ...           ...
2346        Earthy    Woody          Pine
2347         Sweet    Berry         Grape
2348        Earthy    Sweet  Spicy/Herbal
2349         Sweet   Earthy       Pungent
2350         Berry   Earthy       Pungent

[2351 rows x 3 columns]

# Spliting the Effects column

In [18]:
split_data = data["Effects"].str.split(",").to_list()
names = ["Effect_1", "Effect_2", "Effect_3", "Effect_4", "Effect_5"]

new_effect = pd.DataFrame(split_data, columns=names).fillna("None")

In [19]:
new_effect

Effect_1   Effect_2   Effect_3   Effect_4   Effect_5
0     Creative  Energetic     Tingly   Euphoric    Relaxed
1      Relaxed    Aroused   Creative      Happy  Energetic
2     Uplifted      Happy    Relaxed  Energetic   Creative
3       Tingly   Creative     Hungry    Relaxed   Uplifted
4        Happy    Relaxed   Euphoric   Uplifted  Talkative
...        ...        ...        ...        ...        ...
2346     Happy   Uplifted    Relaxed   Euphoric  Energetic
2347   Relaxed      Happy   Euphoric   Uplifted     Sleepy
2348   Relaxed     Sleepy  Talkative   Euphoric      Happy
2349   Relaxed     Sleepy   Euphoric      Happy     Hungry
2350    Hungry    Relaxed   Uplifted      Happy     Sleepy

[2351 rows x 5 columns]

In [20]:
new_effect.describe()

Effect_1 Effect_2  Effect_3  Effect_4  Effect_5
count      2351     2351      2351      2351      2351
unique       15       15        14        14        14
top     Relaxed    Happy  Euphoric  Euphoric  Uplifted
freq        825      571       413       386       273

# Feature Hasher

In [21]:
from sklearn.feature_extraction import FeatureHasher

In [22]:
effect_hasher = FeatureHasher(n_features=3, input_type="string")
x = effect_hasher.fit_transform(total_effects)

In [23]:
print(total_effects)
print(x.toarray())
len(np.unique(x.toarray(), axis=0))

['Creative', 'Energetic', 'Tingly', 'Euphoric', 'Relaxed', 'Aroused', 'Happy', 'Uplifted', 'Hungry', 'Talkative', 'None', 'Giggly', 'Focused', 'Sleepy', 'Dry', 'Mouth']
[[-3.  3.  0.]
 [-2.  3. -2.]
 [-2.  0.  0.]
 [-1.  3. -2.]
 [ 1.  3.  3.]
 [-1.  6.  0.]
 [-2.  2.  1.]
 [-3.  1.  2.]
 [-1.  4. -1.]
 [-2.  0.  1.]
 [-1.  2. -1.]
 [ 0.  1. -1.]
 [-1.  4. -2.]
 [-2.  3.  1.]
 [ 0.  2.  1.]
 [-1.  3. -1.]]


16

In [24]:
flavor_hasher = FeatureHasher(n_features=10, input_type="string")
y = flavor_hasher.fit_transform(total_flavor)

In [25]:
print(total_flavor)
print(y.toarray())
len(np.unique(y.toarray(), axis=0))

['None', 'Earthy', 'Sweet', 'Citrus', 'Flowery', 'Violet', 'Diesel', 'Spicy/Herbal', 'Sage', 'Woody', 'Apricot', 'Grapefruit', 'Orange', 'Pungent', 'Grape', 'Pine', 'Skunk', 'Berry', 'Pepper', 'Menthol', 'Blue', 'Cheese', 'Chemical', 'Mango', 'Lemon', 'Peach', 'Vanilla', 'Nutty', 'Chestnut', 'Tea', 'Tobacco', 'Tropical', 'Strawberry', 'Blueberry', 'Mint', 'Apple', 'Honey', 'Lavender', 'Lime', 'Coffee', 'Ammonia', 'Minty', 'Tree', 'Fruit', 'Butter', 'Pineapple', 'Tar', 'Rose', 'Plum', 'Pear']
[[ 0.  0.  0.  1. -1.  0.  0. -1.  0.  1.]
 [ 1.  0.  0.  0.  1.  0.  0.  1.  0. -1.]
 [ 0. -1.  0.  0.  0.  0.  0.  0. -1.  1.]
 [ 0. -2.  1.  0.  0.  1.  0.  0.  0. -2.]
 [ 0. -1.  1.  1.  1.  1.  0.  0. -1.  1.]
 [ 0. -1.  1.  1.  0.  0.  0.  0.  0.  1.]
 [ 0. -1.  1.  0.  0.  0.  1.  0.  0.  1.]
 [ 1. -2.  1.  0.  1.  1. -1. -1. -1.  3.]
 [ 1.  0. -1.  0.  0.  0.  0.  0. -1.  1.]
 [ 0.  0.  0.  2.  0.  0.  0.  0.  0.  1.]
 [ 0. -1.  1.  1.  0.  1. -1. -1.  0. -1.]
 [ 1. -1.  1.  1.  0.  2. -1. 

50

# Convert flavor and effects to numerical data

In [26]:
total_effects

['Creative',
 'Energetic',
 'Tingly',
 'Euphoric',
 'Relaxed',
 'Aroused',
 'Happy',
 'Uplifted',
 'Hungry',
 'Talkative',
 'None',
 'Giggly',
 'Focused',
 'Sleepy',
 'Dry',
 'Mouth']

In [27]:
names = ["Effect_1", "Effect_2", "Effect_3", "Effect_4", "Effect_5"]
num_effect = pd.DataFrame([])
for name in names:
    d = new_effect[name]
    temp = effect_hasher.transform(d).toarray()
    temp = pd.DataFrame(temp)
    num_effect = pd.concat([num_effect, temp], axis=1)
    

In [28]:
print(num_effect.head(3))
print(new_effect.head(3))

     0    1    2    0    1    2    0    1    2    0    1    2    0    1    2
0 -3.0  3.0  0.0 -2.0  3.0 -2.0 -2.0  0.0  0.0 -1.0  3.0 -2.0  1.0  3.0  3.0
1  1.0  3.0  3.0 -1.0  6.0  0.0 -3.0  3.0  0.0 -2.0  2.0  1.0 -2.0  3.0 -2.0
2 -3.0  1.0  2.0 -2.0  2.0  1.0  1.0  3.0  3.0 -2.0  3.0 -2.0 -3.0  3.0  0.0
   Effect_1   Effect_2  Effect_3   Effect_4   Effect_5
0  Creative  Energetic    Tingly   Euphoric    Relaxed
1   Relaxed    Aroused  Creative      Happy  Energetic
2  Uplifted      Happy   Relaxed  Energetic   Creative


In [29]:
names = ["Flavor_1", "Flavor_2", "Flavor_3"]
num_flavor = pd.DataFrame([])
for name in names:
    d = new_flavor[name]
    temp = flavor_hasher.transform(d).toarray()
    temp = pd.DataFrame(temp)
    num_flavor = pd.concat([num_flavor, temp], axis=1)

In [30]:
num_flavor.head(3)
# print(new_flavor.head(1))

0    1    2    3    4    5    6    7    8    9  ...    0    1    2    3  \
0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0 -1.0  ...  0.0 -2.0  1.0  0.0   
1  0.0 -1.0  1.0  1.0  1.0  1.0  0.0  0.0 -1.0  1.0  ...  0.0 -1.0  1.0  0.0   
2  1.0 -2.0  1.0  0.0  1.0  1.0 -1.0 -1.0 -1.0  3.0  ...  0.0  0.0  0.0  2.0   

     4    5    6    7    8    9  
0  0.0  1.0  0.0  0.0  0.0 -2.0  
1  0.0  0.0  1.0  0.0  0.0  1.0  
2  0.0  0.0  0.0  0.0  0.0  1.0  

[3 rows x 30 columns]

In [31]:
new_data = data.copy()

In [32]:
new_data = pd.get_dummies(new_data, columns=["Type"])
new_data

Strain  Rating                                     Effects  \
0             100-Og     4.0  Creative,Energetic,Tingly,Euphoric,Relaxed   
1     98-White-Widow     4.7    Relaxed,Aroused,Creative,Happy,Energetic   
2               1024     4.4   Uplifted,Happy,Relaxed,Energetic,Creative   
3           13-Dawgs     4.2     Tingly,Creative,Hungry,Relaxed,Uplifted   
4           24K-Gold     4.6   Happy,Relaxed,Euphoric,Uplifted,Talkative   
...              ...     ...                                         ...   
2346         Zeus-Og     4.7   Happy,Uplifted,Relaxed,Euphoric,Energetic   
2347        Zkittlez     4.6      Relaxed,Happy,Euphoric,Uplifted,Sleepy   
2348     Zombie-Kush     5.0     Relaxed,Sleepy,Talkative,Euphoric,Happy   
2349       Zombie-Og     4.4        Relaxed,Sleepy,Euphoric,Happy,Hungry   
2350        Zoom-Pie     4.6        Hungry,Relaxed,Uplifted,Happy,Sleepy   

                         Flavor  \
0           Earthy,Sweet,Citrus   
1         Flowery,Violet,Diesel   
2       Spicy/Herbal,Sage,Woody   
3     Apricot,Citrus,Grapefruit   
4          Citrus,Earthy,Orange   
...                         ...   
2346          Earthy,Woody,Pine   
2347          Sweet,Berry,Grape   
2348  Earthy,Sweet,Spicy/Herbal   
2349       Sweet,Earthy,Pungent   
2350       Berry,Earthy,Pungent   

                                            Description  Type_hybrid  \
0     $100 OG is a 50/50 hybrid strain that packs a ...            1   
1     The ‘98 Aloha White Widow is an especially pot...            1   
2     1024 is a sativa-dominant hybrid bred in Spain...            0   
3     13 Dawgs is a hybrid of G13 and Chemdawg genet...            1   
4     Also known as Kosher Tangie, 24k Gold is a 60%...            1   
...                                                 ...          ...   
2346  Zeus OG is a hybrid cross between Pineapple OG...            1   
2347  Zkittlez is an indica-dominant mix of Grape Ap...            0   
2348  Zombie Kush by Ripper Seeds comes from two dif...            0   
2349  If you’re looking to transform into a flesh-ea...            0   
2350  Zoom Pie (also known as Zombie Pie) is a heavy...            0   

      Type_indica  Type_sativa  
0               0            0  
1               0            0  
2               0            1  
3               0            0  
4               0            0  
...           ...          ...  
2346            0            0  
2347            1            0  
2348            1            0  
2349            1            0  
2350            1            0  

[2351 rows x 8 columns]

In [33]:
new_data = new_data.drop(columns=["Strain", "Effects", "Flavor", "Description"])
new_data = pd.concat([new_data, num_effect, num_flavor], axis=1)
new_data

Rating  Type_hybrid  Type_indica  Type_sativa    0    1    2    0    1  \
0        4.0            1            0            0 -3.0  3.0  0.0 -2.0  3.0   
1        4.7            1            0            0  1.0  3.0  3.0 -1.0  6.0   
2        4.4            0            0            1 -3.0  1.0  2.0 -2.0  2.0   
3        4.2            1            0            0 -2.0  0.0  0.0 -3.0  3.0   
4        4.6            1            0            0 -2.0  2.0  1.0  1.0  3.0   
...      ...          ...          ...          ...  ...  ...  ...  ...  ...   
2346     4.7            1            0            0 -2.0  2.0  1.0 -3.0  1.0   
2347     4.6            0            1            0  1.0  3.0  3.0 -2.0  2.0   
2348     5.0            0            1            0  1.0  3.0  3.0 -2.0  3.0   
2349     4.4            0            1            0  1.0  3.0  3.0 -2.0  3.0   
2350     4.6            0            1            0 -1.0  4.0 -1.0  1.0  3.0   

        2  ...    0    1    2    3    4    5    6    7    8    9  
0    -2.0  ...  0.0 -2.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0 -2.0  
1     0.0  ...  0.0 -1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  
2     1.0  ...  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0  1.0  
3     0.0  ...  1.0 -1.0  1.0  1.0  0.0  2.0 -1.0  0.0  0.0  1.0  
4     3.0  ...  1.0  0.0  0.0  0.0 -1.0  1.0  0.0  0.0  0.0  1.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
2346  2.0  ...  0.0 -2.0  0.0  0.0 -1.0  0.0  0.0  0.0  0.0  1.0  
2347  1.0  ...  1.0  0.0  0.0  0.0  0.0  1.0 -1.0  0.0  0.0  2.0  
2348  1.0  ...  1.0 -2.0  1.0  0.0  1.0  1.0 -1.0 -1.0 -1.0  3.0  
2349  1.0  ...  0.0 -1.0  0.0  0.0 -2.0  0.0  0.0  0.0  0.0  0.0  
2350  3.0  ...  0.0 -1.0  0.0  0.0 -2.0  0.0  0.0  0.0  0.0  0.0  

[2351 rows x 49 columns]

# Modeling

In [34]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist 

In [35]:
# Suppose a customer smoked the 100-Og cannabis and like it. So, I took the features of 100-Og and predicted the recommendations.
test_values = [ 4.,  1.,  0.,  0., -3.,  3.,  0., -2.,  3., -2., -2.,  0.,  0.,
       -1.,  3., -2.,  1.,  3.,  3.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
        1.,  0., -1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  1.,
        0., -2.,  1.,  0.,  0.,  1.,  0.,  0.,  0., -2.]

In [36]:
kmeans = KMeans(n_jobs = -1, n_clusters = 30, init='k-means++', max_iter=500)
model = kmeans.fit(new_data)
test_values = np.array(test_values)
test_values = np.reshape(test_values, (1, -1))
model.predict(test_values)

array([25])

In [37]:
# KMeans Clustering
# converting the results into a dataframe and plotting them
frame = pd.DataFrame({'Cluster':range(1,100), 'Dist': Dist})
plt.figure(figsize=(50,25))
plt.plot(frame['Cluster'], frame['Dist'], marker='o')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')

Exception: Data must be 1-dimensional

In [ ]:
from sklearn.neighbors import NearestNeighbors
nbrs = NearestNeighbors(n_neighbors=5).fit(new_data)

In [ ]:
dist, recommends = nbrs.kneighbors([test_values])
print(dist)
print(recommends)

In [ ]:
for index in recommends[0]:
    print(data.values[index])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
res = cosine_similarity(new_data)
print(res)